### ISSUE TITLE
blog에도 남겼는데 혹시나 하여 같은 내용으로 에러를 남겨봅니다.

### ISSUE THREAD

**Issue by github-mckim** [kjhok1811/spring-jxls-excel-example#1]
excel 다운로드 테스트를 구현해 보고 있는데 에러가 발생합니다.
버전문제인지 잘못 코딩한건지 확인가능할까요?

**예제 수정 소스 .....
    excelDown.do** 

String downloadFileName = "studyList";
		
String title = "Study List";
		
ClassPathResource classPathResource = new ClassPathResource("templates/excel/studyList.xlsx"); 
// resource 에 제공해주신 xlsx파일을 복사해 두어도 null 에러 발생함
FileInputStream fis = new FileInputStream("D:/01_DevSetup/workspace_YYRRIS_Ver03/yyrris/src/main/resources/templates/excel/studyList.xlsx");
// 절대 경로를 fileInputStream으로 설정해도 null 에러 발생..ㅠㅠ
LOGGER.debug("############### excel classPathResource : "+ classPathResource.toString());
		
//        try (InputStream inputStream = new BufferedInputStream(classPathResource.getInputStream())) {
		try (InputStream inputStream = new BufferedInputStream(fis)) {
            response.setHeader(HttpHeaders.CONTENT_DISPOSITION, FileUtils.getExcelFileName(downloadFileName));
            OutputStream outputStream = response.getOutputStream();

            Context context = new Context();
            context.putVar("title", title);
            context.putVar("list", sampleData());
            JxlsHelper.getInstance().processTemplate(inputStream, outputStream, context);
            outputStream.close();
        } catch (IOException e) {
        	LOGGER.error("################# ERROR why??? " );
        	
            throw new RuntimeException(e);
        }

**에러 메세지** 

2022-01-11 15:59:03,646 DEBUG [kr.kmap.module.map.web.MapController] ############### excel Down load sample 
2022-01-11 15:59:03,647 DEBUG [kr.kmap.module.map.web.MapController] ############### excel classPathResource : class path resource [templates/excel/studyList.xlsx]
2022-01-11 15:59:03,662 DEBUG [org.jxls.template.SimpleExporter] SPI org.jxls.util.ServiceFactory => org.jxls.util.ServiceFactoryDefaultImpl@58800b21
2022-01-11 15:59:03,662  INFO [org.jxls.template.SimpleExporter] you may change the SPI on file: META-INF/services/org.jxls.util.ServiceFactory
2022-01-11 15:59:03,666 DEBUG [org.jxls.template.SimpleExporter] SPI org.jxls.util.JxlsConfigProvider => org.jxls.util.JxlsConfigProviderImpl@714eab54
2022-01-11 15:59:03,666  INFO [org.jxls.template.SimpleExporter] you may change the SPI on file: META-INF/services/org.jxls.util.JxlsConfigProvider
2022-01-11 15:59:03,683  INFO [org.jxls.util.TransformerFactory] Loading transformer by class org.jxls.transform.poi.PoiTransformer
2022-01-11 15:59:03,691 DEBUG [org.jxls.util.TransformerFactory] Transformer class is org.jxls.transform.poi.PoiTransformer
2022-01-11 15:59:04,380 ERROR [org.jxls.util.TransformerFactory] Method createTransformer of org.jxls.transform.poi.PoiTransformer class thrown an Exception
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at org.jxls.util.TransformerFactory.createTransformer(TransformerFactory.java:43) [jxls-2.11.0.jar:?]
	at org.jxls.util.JxlsHelper.createTransformer(JxlsHelper.java:471) _[jxls-2.11.0.jar:?]_ <-- 버전문제인가요?
	at org.jxls.util.JxlsHelper.processTemplate(JxlsHelper.java:252) _[jxls-2.11.0.jar:?]_
	at kr.kmap.module.map.web.MapController.excelDown(MapController.java:278) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]

**Comment by kjhok1811** [comment]
안녕하세요. 제가보기엔 라이브러리 버전문제로 보입니다. 현재 제 PC에서 돌려보았는데 문제없이 정상적으로 돌아간거 확인하였습니다.  .m2 디렉토리의 내용을 전부 삭제하신 후 다시한번 테스트 돌려보세요

**Comment by kjhok1811** [comment]
해당이슈는 닫겠습니다.
